services:
  - postgres
jobs:
  include:
    - addons:
        postgres: 9.5
    - addons:
        postgres: 9.6
    - addons:
        postgres: 10
    - addons:
        postgres: 11
script: psql --version
