services:
  - postgres
jobs:
  include:
    - addons:
        postgres: 9.5
    - addons:
        postgres: 9.6
    - addons:
        postgres: 10
    - addons:
        postgres: 11
        apt:
          packages:
            - postgresql-11
            - postgresql-client-11
      env:
        - PGPORT=5433
before_install:
  - ls /etc/postgresql
  - sudo apt-get install -y postgresql-11 postgresql-client-11
  - sudo cp /etc/postgresql/{10,11}/main/pg_hba.conf
  - sudo service postgresql restart 11
before_script:
  - psql -c "create database test;" -U postgres
script: psql --version
